'use strict';

function buildStageAssets(folder) {
  return {
    1: `assets/characters/${folder}/stage-1.png`,
    2: `assets/characters/${folder}/stage-2.png`,
    3: `assets/characters/${folder}/stage-3.png`,
    4: `assets/characters/${folder}/stage-4.png`,
  };
}

function createCharacter(config) {
  return {
    id: config.id,
    name: config.name,
    tagline: config.tagline,
    styleKey: config.styleKey,
    assetSource: config.assetSource || 'placeholder',
    stageAssetPaths: buildStageAssets(config.folder),
    artDirection: {
      palette: config.palette,
      hair: config.hair,
      outfit: config.outfit,
      accessories: config.accessories || [],
      vibe: config.vibe,
      silhouette: config.silhouette,
      promptTags: config.promptTags || [],
    },
    stageNotes: {
      1: config.stages?.[1] || '',
      2: config.stages?.[2] || '',
      3: config.stages?.[3] || '',
      4: config.stages?.[4] || '',
    },
  };
}

const CHARACTER_OPTIONS = [
  createCharacter({
    id: 'cotton-lulu',
    name: '棉花露露',
    tagline: '草莓软糖系',
    styleKey: 'cute',
    folder: 'cotton-lulu',
    assetSource: 'user-provided',
    palette: ['strawberry cream', 'butter yellow', 'marshmallow pink'],
    hair: 'pastel blonde twin buns with star clips and short fluffy bangs',
    outfit: 'strawberry milk mini dress with puff sleeves, ribbon bow and cute doll-like hem',
    accessories: ['star hair clips', 'pink ribbon bows'],
    vibe: 'super cute cartoon girl, candy-sweet, soft and playful',
    silhouette: 'shorter chibi-like body proportion, front-facing full body pose, rounded adorable shape',
    promptTags: ['cute cartoon', 'kawaii doll', 'strawberry pastel', 'little girl style'],
    stages: {
      1: 'roundest cheeks and torso, plush candy-like silhouette with the softest body curve',
      2: 'slightly reduced waist and legs, still soft and sweet with doll-like proportions',
      3: 'clear slimming through waist and limbs while keeping the cute rounded face',
      4: 'lightest cartoon silhouette, neat long leg line and most polished candy-doll finish',
    },
  }),
  createCharacter({
    id: 'cream-latte',
    name: '奶霜拿铁',
    tagline: '温柔知性系',
    styleKey: 'soft',
    folder: 'cream-latte',
    palette: ['milky beige', 'latte brown', 'warm blush'],
    hair: 'dark brown low bun with soft fringe',
    outfit: 'warm beige fitted knit dress with soft clean contours',
    accessories: ['small pearl stud earrings'],
    vibe: 'gentle, composed, warm and mature sweet style',
    silhouette: 'soft oval body shape, elegant centered pose, refined neck and shoulders',
    promptTags: ['soft girl', 'gentle editorial', 'minimal clean fashion illustration'],
    stages: {
      1: 'gentle rounded face, fuller torso and thigh shape, cozy softness',
      2: 'slightly more defined waist and shoulders, posture steadier',
      3: 'lighter torso, slimmer arms, facial features more lifted',
      4: 'most elegant and airy version, slim lines with warm composure',
    },
  }),
  createCharacter({
    id: 'mint-breeze',
    name: '薄荷清风',
    tagline: '清新校园系',
    styleKey: 'fresh',
    folder: 'mint-breeze',
    palette: ['mint green', 'seafoam', 'soft aqua'],
    hair: 'deep teal bob with round bangs and a tiny red accent clip',
    outfit: 'mint fitted dress with clean sporty sweetness',
    accessories: ['small accent clip'],
    vibe: 'fresh campus energy, airy and bright',
    silhouette: 'compact rounded torso, front-facing, youthful proportions',
    promptTags: ['fresh ins style', 'clean pastel illustration', 'light playful mood'],
    stages: {
      1: 'roundest face and midsection, playful softness',
      2: 'slightly tightened waist, more upright stance',
      3: 'clear slimming through torso and arms, fresher expression',
      4: 'light sporty finish, crisp silhouette and lively confidence',
    },
  }),
  createCharacter({
    id: 'berry-night',
    name: '莓果夜语',
    tagline: '冷艳御姐系',
    styleKey: 'cool',
    folder: 'peach-soda',
    palette: ['berry purple', 'midnight plum', 'cool pink'],
    hair: 'sleek dark hair bun with straighter heavy bangs',
    outfit: 'berry purple fitted dress with a slightly sharper waist curve',
    vibe: 'cool, glam, polished and a bit aloof',
    silhouette: 'same body template with slightly sharper visual styling',
    promptTags: ['cool ins girl', 'purple gradient', 'editorial cute character'],
    stages: {
      1: 'fuller soft-glam silhouette with round cheeks',
      2: 'mild waist definition, stronger posture',
      3: 'cleaner face shape, visibly lighter torso',
      4: 'coolest and sharpest linework, sleek final silhouette',
    },
  }),
  createCharacter({
    id: 'apricot-sun',
    name: '杏子晴光',
    tagline: '暖甜治愈系',
    styleKey: 'warm',
    folder: 'cream-latte',
    palette: ['apricot', 'warm honey', 'soft cream'],
    hair: 'dark hair bun with rounded fringe and warmer highlights',
    outfit: 'apricot fitted dress, sunlit and comforting',
    vibe: 'warm, healing, softly cheerful',
    silhouette: 'round and friendly, same stable centered pose',
    promptTags: ['warm ins palette', 'healing mood', 'pastel fashion figure'],
    stages: {
      1: 'plush and comforting body shape',
      2: 'gentle tightening through waist and arms',
      3: 'lighter core silhouette with sunny expression',
      4: 'most radiant and airy version with warm glow',
    },
  }),
  createCharacter({
    id: 'ocean-star',
    name: '海盐星芒',
    tagline: '清冷海风系',
    styleKey: 'clean',
    folder: 'mint-breeze',
    palette: ['sea blue', 'salt white', 'sky blue'],
    hair: 'ink-blue bob with crisp fringe',
    outfit: 'sea-blue fitted dress with cool glossy shading',
    vibe: 'clean, breezy, quiet ocean freshness',
    silhouette: 'slim visual styling while keeping the same front-centered template',
    promptTags: ['sea breeze', 'cool pastel', 'clean stylish character'],
    stages: {
      1: 'softest ocean silhouette with fuller midsection',
      2: 'cleaner waist edge, more open chest posture',
      3: 'clear slimming in limbs and face, cooler airiness',
      4: 'most refined and crisp sea-breeze finish',
    },
  }),
  createCharacter({
    id: 'rose-cocoa',
    name: '玫瑰可可',
    tagline: '复古甜心系',
    styleKey: 'retro',
    folder: 'peach-soda',
    palette: ['dusty rose', 'cocoa mauve', 'cream pink'],
    hair: 'dark retro bun with rounded fringe and soft curl suggestion',
    outfit: 'dusty rose fitted dress with retro sweetness',
    vibe: 'vintage sweet, mellow, slightly dreamy',
    silhouette: 'same centered fashion-doll template, softer romantic finish',
    promptTags: ['retro ins', 'dusty rose palette', 'soft romantic character'],
    stages: {
      1: 'most plush and romantic shape',
      2: 'subtle waist refinement and lifted pose',
      3: 'lighter lines with elegant face lift',
      4: 'retro heroine feel, airy and polished',
    },
  }),
  createCharacter({
    id: 'lemon-fizz',
    name: '柠檬轻泡',
    tagline: '活力运动系',
    styleKey: 'sport',
    folder: 'mint-breeze',
    palette: ['lemon cream', 'lime', 'sun yellow'],
    hair: 'dark sporty bob with neat bangs',
    outfit: 'lemon-toned fitted sporty dress, bright and brisk',
    vibe: 'energetic, sparkling, active and sunny',
    silhouette: 'same front-facing base with slightly more lively energy',
    promptTags: ['sporty sweet', 'bright pastel', 'fresh active girl'],
    stages: {
      1: 'rounder athletic softness with plush torso',
      2: 'slightly more defined waist and lifted stance',
      3: 'leaner sporty silhouette through arms and legs',
      4: 'most energetic slim finish with sparkly confidence',
    },
  }),
  createCharacter({
    id: 'moon-iris',
    name: '月鸢流光',
    tagline: '梦幻仙气系',
    styleKey: 'dream',
    folder: 'moon-iris',
    assetSource: 'user-provided',
    palette: ['lavender mist', 'moon white', 'soft iris'],
    hair: 'dark plum bun with soft rounded bangs',
    outfit: 'lavender fitted dress with airy dreamy sheen',
    vibe: 'dreamy, ethereal, soft glowing elegance',
    silhouette: 'same centered template with softer luminous finishing',
    promptTags: ['dreamy ins style', 'ethereal pastel', 'soft glow character'],
    stages: {
      1: 'cloud-soft face and torso with dreamy roundness',
      2: 'slight slimming and more lifted neck line',
      3: 'airier core and limbs, clearer face shape',
      4: 'most floating and luminous final silhouette',
    },
  }),
];

function getCharacterById(characterId) {
  return CHARACTER_OPTIONS.find((c) => c.id === characterId) || CHARACTER_OPTIONS[0];
}

module.exports = {
  CHARACTER_OPTIONS,
  getCharacterById,
};
