'use strict';

function buildStageAssets(folder) {
  return {
    1: `assets/characters/${folder}/stage-1.png`,
    2: `assets/characters/${folder}/stage-2.png`,
    3: `assets/characters/${folder}/stage-3.png`,
    4: `assets/characters/${folder}/stage-4.png`,
  };
}

function createCharacter(config) {
  return {
    id: config.id,
    name: config.name,
    tagline: config.tagline,
    styleKey: config.styleKey,
    assetSource: config.assetSource || 'placeholder',
    stageAssetPaths: buildStageAssets(config.folder),
    artDirection: {
      palette: config.palette,
      hair: config.hair,
      outfit: config.outfit,
      accessories: config.accessories || [],
      vibe: config.vibe,
      silhouette: config.silhouette,
      promptTags: config.promptTags || [],
    },
    stageNotes: {
      1: config.stages?.[1] || '',
      2: config.stages?.[2] || '',
      3: config.stages?.[3] || '',
      4: config.stages?.[4] || '',
    },
  };
}

const CHARACTER_OPTIONS = [
  createCharacter({
    id: 'cotton-lulu',
    name: '热汗晴夏',
    tagline: '燃脂健身系',
    styleKey: 'sport',
    folder: 'cotton-lulu',
    assetSource: 'user-provided',
    palette: ['charcoal black', 'coral pink', 'soft gym pink'],
    hair: 'dark brown high ponytail with soft loose bangs',
    outfit: 'black fitted gym set with coral side panels, tight training shorts and white sneakers',
    accessories: ['pink sweat towel', 'sport wristbands'],
    vibe: 'sweet gym heroine, healthy, energetic and confident',
    silhouette: 'same centered full-body template with a clearly readable fuller-to-slim fitness transformation',
    promptTags: ['gym style', 'sporty heroine', 'fitness fashion', 'high ponytail training look'],
    stages: {
      1: 'clearly chubby fitness silhouette, with the fullest waist, hips, thighs and calves at a glance',
      2: 'still visibly plump and athletic, only a little lighter than stage 1 with a broad waist and heavy thighs',
      3: 'noticeably slimmer through waist, belly, arms and legs, with a cleaner jawline while keeping the same sporty identity',
      4: 'lightest and most polished gym silhouette, strongest glow-up contrast from stage 1 with the cleanest athletic leg line',
    },
  }),
  createCharacter({
    id: 'cream-latte',
    name: '雾纱心铃',
    tagline: '纯欲轻纱系',
    styleKey: 'soft',
    folder: 'mist-bell',
    assetSource: 'user-provided',
    palette: ['misty blush', 'soft black', 'sheer rose'],
    hair: 'long deep-brown softly wavy hair with airy bangs and large watery eyes',
    outfit: 'sheer rose chiffon top with black fitted mini skirt, black thigh-high stockings and slim heels',
    accessories: ['black choker', 'thigh-high stockings'],
    vibe: 'fragile pure-desire glamour, soft, wistful and delicately alluring',
    silhouette: 'same centered full-body template with a clearly readable fuller-to-slim transformation and refined long-leg styling',
    promptTags: ['pure desire style', 'sheer blouse', 'soft sad eyes', 'delicate mature sweet'],
    stages: {
      1: 'softest and fullest body stage, with a plush waist, fuller belly, thicker thighs and the most fragile gentle expression',
      2: 'still clearly soft and fuller-bodied, only slightly lighter than stage 1 with visible thigh and waist weight',
      3: 'noticeably slimmer through waist, arms and legs, with a cleaner jawline while keeping the same tender expression',
      4: 'lightest and most refined pure-desire silhouette, with the strongest glow-up contrast from stage 1 and the cleanest leg line',
    },
  }),
  createCharacter({
    id: 'mint-breeze',
    name: '樱雾诗织',
    tagline: '软萌校园系',
    styleKey: 'fresh',
    folder: 'mint-breeze',
    assetSource: 'user-provided',
    palette: ['soft white', 'blush pink', 'deep navy'],
    hair: 'dark brown short bob with light wispy bangs and a small hair clip',
    outfit: 'white short-sleeve academy blouse with pale pink ribbon bow and navy pleated skirt',
    accessories: ['small silver hair clip', 'pink ribbon bow'],
    vibe: 'soft shy campus fashion, gentle, polished and sweet',
    silhouette: 'same centered full-body template with a clearly readable fuller-to-slim school fashion transformation',
    promptTags: ['academy-inspired outfit', 'soft blush campus girl', 'short bob hairstyle', 'clean school fashion'],
    stages: {
      1: 'clearly chubby school-fashion silhouette, with the fullest cheeks, waist, hips and thighs at a glance',
      2: 'still visibly plump and soft, only a little lighter than stage 1 with a broad waist and heavy thighs',
      3: 'noticeably slimmer through waist, arms and legs, with a cleaner face shape while keeping the same gentle identity',
      4: 'lightest and most polished campus silhouette, strongest glow-up contrast from stage 1 with the cleanest leg line',
    },
  }),
  createCharacter({
    id: 'berry-night',
    name: '紫澜夏音',
    tagline: '梦幻泳装系',
    styleKey: 'dream',
    folder: 'peach-soda',
    assetSource: 'user-provided',
    palette: ['lavender mist', 'orchid purple', 'pearl white'],
    hair: 'long soft lavender hair with glossy curls and a pearl hair clip',
    outfit: 'lavender one-piece swimsuit with delicate frill trim and soft shell-like detailing',
    accessories: ['pearl hair clip'],
    vibe: 'dreamy beach glamour, soft, elegant and lightly ethereal',
    silhouette: 'centered full-body swimsuit silhouette with a clearly readable slimming journey',
    promptTags: ['lavender swimsuit', 'dreamy mature sweet', 'soft glow fashion illustration'],
    stages: {
      1: 'softest face and fullest waist-thigh silhouette, clearly plush and curvy at a glance',
      2: 'still visibly soft and fuller-bodied, only slightly lighter than stage 1',
      3: 'cleaner waistline and slimmer leg shape while keeping the same glamorous bust and face',
      4: 'lightest lavender-beach silhouette, longest leg line and most polished dreamy glow-up',
    },
  }),
  createCharacter({
    id: 'apricot-sun',
    name: '糖心公主',
    tagline: '梦幻公主系',
    styleKey: 'warm',
    folder: 'sugar-princess',
    assetSource: 'user-provided',
    palette: ['princess pink', 'cream pearl', 'soft apricot gold'],
    hair: 'golden-brown twin ponytails with fluffy curled ends and a tiny princess crown',
    outfit: 'pink and cream princess dress with ribbon bows, puff sleeves and layered frill skirt',
    accessories: ['tiny princess crown', 'pearl necklace', 'ribbon bows'],
    vibe: 'dreamy princess sweetness, polished, cute and delicately magical',
    silhouette: 'same centered full-body template with a clearly readable fuller-to-slim transformation in a frilly princess silhouette',
    promptTags: ['princess dress', 'twin tails', 'cute elegant', 'pink ribbon fairy tale'],
    stages: {
      1: 'softest and fullest princess stage, with the plushest waist, thighs and cheeks at a glance',
      2: 'still clearly soft and fuller-bodied, only slightly lighter than stage 1 with visible waist and leg fullness',
      3: 'noticeably slimmer through waist, arms and legs, with a cleaner face shape while keeping the same sweet princess charm',
      4: 'lightest and most polished princess silhouette, strongest contrast from stage 1 with the cleanest final glow-up',
    },
  }),
  createCharacter({
    id: 'ocean-star',
    name: '鎏金秘书',
    tagline: '轻熟白领系',
    styleKey: 'clean',
    folder: 'gold-office',
    assetSource: 'user-provided',
    palette: ['champagne gold', 'clean white', 'navy office blue'],
    hair: 'golden blonde medium-long hair with soft office waves',
    outfit: 'short-sleeve white office blouse with navy fitted tailored trousers and elegant heels',
    accessories: ['slim belt', 'small gold necklace'],
    vibe: 'refined white-collar glamour, polished, mature and softly confident',
    silhouette: 'same centered full-body template with a clearly readable fuller-to-slim office-lady transformation',
    promptTags: ['office lady', 'gold blonde', 'tailored trousers', 'mature commuter style'],
    stages: {
      1: 'softest and fullest office silhouette, with the widest waist-hip span and the heaviest thigh shape at a glance',
      2: 'still clearly soft and fuller-bodied, only slightly lighter than stage 1 with visible waist and thigh fullness',
      3: 'noticeably slimmer through waist, arms and legs, with a cleaner jawline and sharper tailored look',
      4: 'lightest and most refined white-collar silhouette, strongest contrast from stage 1 with the cleanest long-leg finish',
    },
  }),
  createCharacter({
    id: 'rose-cocoa',
    name: '玫瑰可可',
    tagline: '复古甜心系',
    styleKey: 'retro',
    folder: 'rose-cocoa-v2',
    assetSource: 'user-provided',
    palette: ['dusty rose', 'cocoa mauve', 'cream pink'],
    hair: 'dark chestnut soft updo with airy bangs and a small camellia pearl clip',
    outfit: 'dusty rose fitted knit dress with soft cream trim',
    vibe: 'vintage sweet, mellow, slightly dreamy',
    silhouette: 'same centered fashion-doll template, softer romantic finish',
    promptTags: ['retro ins', 'dusty rose palette', 'soft romantic character'],
    stages: {
      1: 'most plush and romantic shape',
      2: 'subtle waist refinement and lifted pose',
      3: 'lighter lines with elegant face lift',
      4: 'retro heroine feel, airy and polished',
    },
  }),
  createCharacter({
    id: 'lemon-fizz',
    name: '蜜桃发球',
    tagline: '甜辣网球系',
    styleKey: 'sport',
    folder: 'lemon-fizz',
    assetSource: 'user-provided',
    palette: ['peach pink', 'soft white', 'tennis blush'],
    hair: 'dark brown high ponytail with soft curled ends',
    outfit: 'white and peach fitted tennis top with pleated tennis skirt and knee-high socks',
    accessories: ['tennis racket', 'sport wristbands'],
    vibe: 'sweet sporty glamour, bright and confident with a peach-toned tennis aesthetic',
    silhouette: 'same front-facing full-body template with a clearly readable chubby-to-slim tennis journey',
    promptTags: ['tennis girl', 'sporty sweet', 'peach pink athletic look', 'glam sporty heroine'],
    stages: {
      1: 'most plush sporty silhouette, with the fullest waist, belly, thighs and calves at a glance',
      2: 'still clearly soft and fuller-bodied, only a little lighter than stage 1 with visible belly and thigh weight',
      3: 'much flatter midsection and cleaner limbs, now clearly slimmer while keeping the same sporty charm',
      4: 'lightest athletic finish, healthiest slim tennis silhouette and strongest glow-up contrast from stage 1',
    },
  }),
  createCharacter({
    id: 'moon-iris',
    name: '板桥澄夏',
    tagline: '街头滑板系',
    styleKey: 'sport',
    folder: 'moon-iris',
    assetSource: 'user-provided',
    palette: ['soft white', 'coral orange', 'skate black'],
    hair: 'dark brown long high ponytail with soft loose strands',
    outfit: 'oversized white skate tee with coral accents and fitted black sporty shorts',
    accessories: ['sport wristbands', 'street sneakers'],
    vibe: 'soft sporty street girl, bright, relaxed and lightly playful',
    silhouette: 'same centered full-body template with a clearly readable fuller-to-slim skateboard-girl transformation',
    promptTags: ['skate girl', 'street sport', 'oversized tee', 'long ponytail'],
    stages: {
      1: 'clearly chubby street-sport silhouette, with the fullest waist, hips, thighs and calves at a glance',
      2: 'still visibly plump and sporty, only a little lighter than stage 1 with a broad waist and heavy thighs',
      3: 'noticeably slimmer through waist, belly, arms and legs, with a cleaner jawline while keeping the same skate-girl identity',
      4: 'lightest and most polished street-athletic silhouette, strongest glow-up contrast from stage 1 with the cleanest long-leg finish',
    },
  }),
];

function getCharacterById(characterId) {
  return CHARACTER_OPTIONS.find((c) => c.id === characterId) || CHARACTER_OPTIONS[0];
}

module.exports = {
  CHARACTER_OPTIONS,
  getCharacterById,
};
