'use strict';

const DEFAULT_INITIAL_WEIGHT = 130;
const DEFAULT_TARGET_WEIGHT = 100;

const MIN_ALLOWED_WEIGHT = 30;
const MAX_ALLOWED_WEIGHT = 300;

const CLASSIC_MODE_DURATION_SECONDS = 60;
const BASE_DOCK_SIZE = 6;
const MAX_EARNED_DOCK_BOOSTS = 2;

const COMBO_WINDOW_MS = 4000;
const MATCH_RESOLVE_DELAY_MS = 300;
const SPECIAL_EFFECT_DURATION_MS = 2000;
const SPECIAL_EFFECT_SETTLE_MS = 600;
const REBOUND_WEIGHT_ANIMATION_MS = 1800;
const REBOUND_MODAL_DURATION_MS = 2500;
const MATCH_SCORE = 30;
const SLASH_SCORE_PER_TILE = 15;
const SLASH_WEIGHT_DROP_FACTOR = 0.4;

const SLIM_BOOST_CONSECUTIVE_SAME_TYPE = 3;
const SLIM_BOOST_COOLDOWN_TRIPLES = 5;
const SLIM_BOOST_WEIGHT_MULTIPLIER = 1.5;

const SWEET_SLASH_MIN_CONSECUTIVE_SAME_TYPE = 4;
const SWEET_SLASH_MAX_PER_GAME = 99;
const SWEET_SLASH_BASE_DURATION_MS = 10000;
const SWEET_SLASH_MAX_DURATION_MS = 10000;
const SWEET_SLASH_BONUS_PER_HIT_MS = 0;
const SWEET_SLASH_SCORE_BASE = 90;
const SWEET_SLASH_SCORE_COMBO_STEP = 24;
const SWEET_SLASH_CONCURRENT_TARGETS = 16;

module.exports = {
  DEFAULT_INITIAL_WEIGHT,
  DEFAULT_TARGET_WEIGHT,
  MIN_ALLOWED_WEIGHT,
  MAX_ALLOWED_WEIGHT,
  CLASSIC_MODE_DURATION_SECONDS,
  BASE_DOCK_SIZE,
  MAX_EARNED_DOCK_BOOSTS,
  COMBO_WINDOW_MS,
  MATCH_RESOLVE_DELAY_MS,
  SPECIAL_EFFECT_DURATION_MS,
  SPECIAL_EFFECT_SETTLE_MS,
  REBOUND_WEIGHT_ANIMATION_MS,
  REBOUND_MODAL_DURATION_MS,
  MATCH_SCORE,
  SLASH_SCORE_PER_TILE,
  SLASH_WEIGHT_DROP_FACTOR,
  SLIM_BOOST_CONSECUTIVE_SAME_TYPE,
  SLIM_BOOST_COOLDOWN_TRIPLES,
  SLIM_BOOST_WEIGHT_MULTIPLIER,
  SWEET_SLASH_MIN_CONSECUTIVE_SAME_TYPE,
  SWEET_SLASH_MAX_PER_GAME,
  SWEET_SLASH_BASE_DURATION_MS,
  SWEET_SLASH_MAX_DURATION_MS,
  SWEET_SLASH_BONUS_PER_HIT_MS,
  SWEET_SLASH_SCORE_BASE,
  SWEET_SLASH_SCORE_COMBO_STEP,
  SWEET_SLASH_CONCURRENT_TARGETS,
};
